title: Luc Paoli
description: A personal portfolio and CV website
author: Luc Paoli author
avatar: /assets/images/profile_photo_sq.png
email: luc@lucpaoli.com

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate

paginate: 10
skin: daylight
subscribe: false

# Uncomment the below line and set the tracking ID for enabling Google Analytics
# 
# google_analytics: 

# Uncomment the below lines and set the Disqus shortname for enabling Disqus
# 
# disqus:

# Jekyll
# ======
# exclude:
#   - scripts/
#   - README.md
#   - jekyll-theme-hamilton.gemspec

# Jekyll SEO Tag (Optional)
# =========================
# logo: 
social:
  links:
    - https://github.com/lucpaoli
    - https://www.linkedin.com/in/luc-paoli/
# google_site_verification: u4WXQl0Eu66rsQo2kRdCNx
lang: en
